---
title: "popular peaks"
author: "Paul Apivat Hanvongse"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries


```{r, echo=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)

df <- read_csv("df.csv")
head(df)
```

## Final Table


```{r final_table, echo=FALSE}

options(reactable.theme = reactableTheme(
    color = "hsl(233, 9%, 87%)",
    backgroundColor = "hsl(233, 9%, 19%)",
    borderColor = "hsl(233, 9%, 22%)",
    stripedColor = "hsl(233, 12%, 22%)",
    highlightColor = "hsl(233, 12%, 24%)",
    inputStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    selectStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    pageButtonHoverStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    pageButtonActiveStyle = list(backgroundColor = "hsl(233, 9%, 28%)")
))


tbl <- reactable(
    df,
    pagination = FALSE,
    defaultSorted = "attempts",
    defaultColDef = colDef(headerClass = "header", align = "left"),
    columns = list(
        peak = colDef(
            name = "Peaks",
            width = 150
        ),
        attempts = colDef(
            name = "Attempts (#)",
            defaultSortOrder = "desc",
            cell = function(value){
                width <- paste0(value * 100 / max(df$attempts), "%")
                value <- format(value, big.mark = ",")
                value <- format(value, width = 9, justify = 'right')
                #bar_chart(value, width = width, fill = "#3fc1c9")
                bar <- div(
                    class = "bar-chart",
                    style = list(marginRight = "6px"),
                    div(class = "bar", style = list(width = width, backgroundColor = "#00b58c"))
                )
                div(class = "bar-cell", span(class = "number", value), bar)
            },
            #align = "left",
            #style = list(fontFamily = "monospace", whiteSpace = "pre")
        ),
        fail_rate = colDef(
            name = "Fail (%)",
            defaultSortOrder = "desc",
            # Format and render the cell with a javascript render function
            cell = JS("function(cellInfo) {
                const pct = (cellInfo.value * 100).toFixed(1) + '%'
                let value = pct.padStart(5)
                if (cellInfo.viewIndex > 0){
                    value = value.replace('%', ' ')
                }
                return (
                    '<div class=\"bar-cell\">' +
                        '<span class=\"number\">' + value + '</span>' +
                        '<div class=\"bar-chart\" style=\"background-color: #e1e1e1\">' +
                            '<div class=\"bar\" style=\"width: ' + pct + '; background-color: #f47983\"></div>' +
                        '</div>' +
                    '</div>'
                )
            }"),
            # Render this column as HTML
            html = TRUE,
            #align = "left"
        )
    ),
    compact = TRUE,
    class = "followers-tbl"
)

```


## Add title and subtitle

```{r, final_demo, eval=TRUE}

div(class = "twitter-followers",
    div(class = "followers-header",
        div(class = "followers-title", "The Most Popular Peaks in the Himalayas"),
        "Sort by Attempts and Fail Rate"
        ),
    tbl
)

```


## CSS for R Markdown

```{css}

/* Styles for the table container, title, and subtitle */

.twitter-followers {
  margin: 0 auto;
  width: 575px;
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.followers-header {
  margin: 8px 0;
  font-size: 16px;
}
.followers-title {
  font-size: 20px;
  font-weight: 600;
}

/* Styles for the table */
    
.followers-tbl {
  font-size: 14px;
  line-height: 18px;
}

.followers-tbl a {
  color: inherit;
}

/* Styles for the column headers */
    
.header {
  border-bottom: 2px solid #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}
.header:hover {
  background-color: #eee;
}

/* Styles for the bar charts */
    
.bar-cell {
  display: flex;
  align-items: center;
}

.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 13.5px;
  white-space: pre;
}

.bar-chart {
  flex-grow: 1;
  margin-left: 6px;
  height: 14px;
}

.bar {
  height: 100%;
}

```

## R Markdown html documents

```{css echo=FALSE}

.main-container {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}
.main-container blockquote {
  font-size: inherit;
}
/* pkgdown articles */
.contents {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}
.contents blockquote {
  font-size: inherit;
}
.reactable {
  font-size: 14px;
}
```